import type { AuditResult } from "./types";

export function generateBrief(decision: string, result: AuditResult): string {
  return `StratOS — Decision Audit

Decision: ${decision}

Readiness Score: ${result.confidence_score}/100
Verdict: ${result.verdict}

Biggest Risk:
${result.biggest_risk}

Hidden Assumption:
${result.hidden_assumption}

Better Question:
${result.better_question}

Stakeholder Gap:
${result.stakeholder_gap}

30-Day Test:
${result.thirty_day_test}

Devil's Argument:
${result.devils_argument}

Generated by StratOS — Executive Decision Intelligence`;
}
