import type { AuditResult } from "./types";

export function generateBrief(decision: string, result: AuditResult): string {
  return `StratOS Lite — London Royal Academy Decision Audit

Decision: ${decision}

Type: ${result.decision_type}

Verdict: ${result.verdict}

Confidence: ${result.confidence_score}/100

Biggest Risk:
${result.biggest_risk}

Hidden Assumption:
${result.hidden_assumption}

Better Question:
${result.better_question}

30-Day Test:
${result.thirty_day_test}

Devil's Argument:
${result.devils_argument}

Generated by StratOS Lite
ai.londonra.com`;
}
