import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import type { AuditResult } from "./types";

export async function generatePDF(decision: string, result: AuditResult): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const { height } = page.getSize();

  const gold = rgb(0.78, 0.65, 0.28);
  const black = rgb(0, 0, 0);
  const gray = rgb(0.4, 0.4, 0.4);
  const white = rgb(1, 1, 1);

  page.drawRectangle({ x: 0, y: 0, width: 595, height: 842, color: white });

  let y = height - 50;

  page.drawText("London Royal Academy", { x: 50, y, size: 10, font: helvetica, color: gray });
  y -= 20;
  page.drawText("StratOS Lite — Decision Audit", { x: 50, y, size: 16, font: helveticaBold, color: black });
  y -= 5;
  page.drawRectangle({ x: 50, y, width: 100, height: 2, color: gold });
  y -= 25;

  // Date stamp
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  page.drawText(`Date: ${dateStr}`, { x: 50, y, size: 9, font: helvetica, color: gray });
  y -= 25;

  // Decision Readiness Score
  page.drawText("DECISION READINESS SCORE", { x: 50, y, size: 10, font: helveticaBold, color: gold });
  y -= 20;
  page.drawText(`${result.confidence_score}/100`, { x: 50, y, size: 24, font: helveticaBold, color: black });
  y -= 16;
  page.drawText(result.confidence_rationale, { x: 50, y, size: 9, font: helvetica, color: gray });
  y -= 25;

  page.drawText("DECISION", { x: 50, y, size: 8, font: helveticaBold, color: gray });
  y -= 16;
  const wrappedDecision = wrapText(decision, 80);
  for (const line of wrappedDecision) {
    page.drawText(line, { x: 50, y, size: 11, font: helvetica, color: black });
    y -= 16;
  }
  y -= 10;

  page.drawText(`VERDICT: ${result.verdict}`, { x: 50, y, size: 14, font: helveticaBold, color: black });
  y -= 30;

  const fields = [
    ["Decision Type", result.decision_type],
    ["Biggest Risk", result.biggest_risk],
    ["Hidden Assumption", result.hidden_assumption],
    ["Better Question", result.better_question],
    ["Stakeholder Gap", result.stakeholder_gap],
    ["30-Day Test", result.thirty_day_test],
    ["Devil's Argument", result.devils_argument],
  ];

  for (const [label, value] of fields) {
    page.drawText(label.toUpperCase(), { x: 50, y, size: 8, font: helveticaBold, color: gold });
    y -= 14;
    const lines = wrapText(value, 85);
    for (const line of lines) {
      page.drawText(line, { x: 50, y, size: 10, font: helvetica, color: black });
      y -= 14;
    }
    y -= 10;
  }

  // Footer
  page.drawText("Generated by StratOS | London Royal Academy | Confidential", { x: 50, y: 30, size: 8, font: helvetica, color: gray });
  page.drawText(dateStr, { x: 420, y: 30, size: 8, font: helvetica, color: gray });

  return doc.save();
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + " " + word).trim().length > maxChars) {
      lines.push(current.trim());
      current = word;
    } else {
      current += " " + word;
    }
  }
  if (current.trim()) lines.push(current.trim());
  return lines;
}
